// <auto-generated />
namespace Final.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class autoinitmigration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(autoinitmigration));
        
        string IMigrationMetadata.Id
        {
            get { return "201310081706526_autoinitmigration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
