// <auto-generated />
namespace Final.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class _101413 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_101413));
        
        string IMigrationMetadata.Id
        {
            get { return "201310150402233_10.14.13"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
